from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

MESSAGE_COLUMNS = (
    "account",
    "message_id",
    "thread_id",
    "history_id",
    "internal_date",
    "label_ids",
    "is_deleted",
    "snippet",
    "subject",
    "from_address",
    "to_addresses",
    "cc_addresses",
    "bcc_addresses",
    "delivered_to",
    "rfc822_message_id",
    "date_header",
    "size_estimate",
    "body_text",
    "body_html",
    "body_markdown",
    "body_markdown_full",
    "body_markdown_clean",
    "payload_json",
    "synced_at",
    "sync_version",
)

ATTACHMENT_COLUMNS = (
    "account",
    "message_id",
    "thread_id",
    "history_id",
    "internal_date",
    "part_id",
    "attachment_id",
    "filename",
    "mime_type",
    "content_id",
    "content_disposition",
    "size",
    "content_sha256",
    "storage_backend",
    "storage_key",
    "storage_file_id",
    "storage_url",
    "storage_status",
    "is_deleted",
    "part_json",
    "synced_at",
    "sync_version",
)

SYNC_STATE_COLUMNS = (
    "account",
    "last_history_id",
    "last_sync_type",
    "status",
    "error",
    "updated_at",
)

ATTACHMENT_BACKFILL_STATE_COLUMNS = (
    "account",
    "message_id",
    "status",
    "attachment_rows_written",
    "error",
    "ai_provider",
    "ai_model",
    "ai_prompt_version",
    "updated_at",
    "sync_version",
)

ATTACHMENT_ENRICHMENT_COLUMNS = (
    "content_sha256",
    "ai_provider",
    "ai_model",
    "ai_prompt_version",
    "text",
    "text_extraction_status",
    "text_extraction_error",
    "ai_base_url",
    "ai_prompt_sha256",
    "ai_prompt",
    "ai_source_status",
    "ai_elapsed_ms",
    "ai_processed_at",
    "updated_at",
    "sync_version",
)

CALENDAR_EVENT_COLUMNS = (
    "account",
    "calendar_id",
    "event_id",
    "recurring_event_id",
    "i_cal_uid",
    "status",
    "is_deleted",
    "summary",
    "description",
    "location",
    "creator_email",
    "organizer_email",
    "start_at",
    "end_at",
    "start_date",
    "end_date",
    "is_all_day",
    "html_link",
    "attendees_json",
    "reminders_json",
    "recurrence",
    "event_type",
    "raw_json",
    "updated_at",
    "synced_at",
    "sync_version",
)

CALENDAR_SYNC_STATE_COLUMNS = (
    "account",
    "calendar_id",
    "sync_token",
    "last_sync_type",
    "status",
    "error",
    "expanded_synced_at",
    "expanded_window_start",
    "expanded_window_end",
    "updated_at",
    "sync_version",
)

CONTACT_CARD_COLUMNS = (
    "source",
    "account",
    "source_kind",
    "address_book_id",
    "card_id",
    "etag",
    "source_uid",
    "display_name",
    "given_name",
    "family_name",
    "organization",
    "job_title",
    "primary_email",
    "primary_phone",
    "emails",
    "phones",
    "addresses",
    "organizations",
    "urls",
    "groups",
    "dates",
    "photos",
    "notes",
    "is_deleted",
    "source_updated_at",
    "synced_at",
    "sync_version",
    "raw_json",
)

CONTACT_SYNC_STATE_COLUMNS = (
    "source",
    "account",
    "source_kind",
    "address_book_id",
    "sync_token",
    "last_sync_type",
    "status",
    "error",
    "full_synced_at",
    "updated_at",
    "sync_version",
)

VOICE_MEMO_FILE_COLUMNS = (
    "account",
    "recording_id",
    "title",
    "original_path",
    "filename",
    "extension",
    "content_type",
    "size_bytes",
    "content_sha256",
    "file_created_at",
    "file_modified_at",
    "recorded_at",
    "storage_backend",
    "storage_key",
    "storage_file_id",
    "storage_url",
    "metadata_storage_key",
    "metadata_storage_file_id",
    "metadata_storage_url",
    "metadata_content_sha256",
    "is_deleted",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

VOICE_MEMO_TRANSCRIPTION_RUN_COLUMNS = (
    "account",
    "recording_id",
    "content_sha256",
    "provider",
    "provider_transcript_id",
    "model",
    "status",
    "error",
    "transcript_text",
    "raw_result_json",
    "requested_at",
    "completed_at",
    "sync_version",
)

RETRYABLE_VOICE_MEMO_TRANSCRIPTION_ERROR_PATTERNS = (
    "current account balance is negative",
    "please top up",
    "upload failed, please try again",
    "too many requests",
    "rate limit",
    "rate limited",
    "timeout",
    "timed out",
    "temporarily",
    "temporary",
    "500 server error",
    "502 server error",
    "503 server error",
    "504 server error",
)

VOICE_MEMO_TRANSCRIPT_SEGMENT_COLUMNS = (
    "account",
    "recording_id",
    "provider",
    "provider_transcript_id",
    "segment_index",
    "speaker_label",
    "start_ms",
    "end_ms",
    "confidence",
    "text",
    "words_json",
    "created_at",
    "sync_version",
)

VOICE_MEMO_ENRICHMENT_COLUMNS = (
    "account",
    "recording_id",
    "content_sha256",
    "provider",
    "model",
    "prompt_version",
    "status",
    "error",
    "calendar_event_id",
    "calendar_confidence",
    "title",
    "start_at",
    "end_at",
    "participants_json",
    "transcript",
    "summary",
    "action_items_json",
    "evidence_json",
    "raw_result_json",
    "created_at",
    "sync_version",
)

APPLE_NOTE_COLUMNS = (
    "account",
    "note_id",
    "latest_revision_id",
    "title",
    "folder_id",
    "folder_path",
    "apple_account_id",
    "apple_account_name",
    "created_at",
    "modified_at",
    "body_text",
    "body_html",
    "body_markdown",
    "content_sha256",
    "attachments_json",
    "storage_backend",
    "metadata_storage_key",
    "metadata_storage_file_id",
    "metadata_storage_url",
    "metadata_content_sha256",
    "html_storage_key",
    "html_storage_file_id",
    "html_storage_url",
    "html_content_sha256",
    "is_deleted",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_NOTE_REVISION_COLUMNS = (
    "account",
    "note_id",
    "revision_id",
    "title",
    "folder_id",
    "folder_path",
    "apple_account_id",
    "apple_account_name",
    "created_at",
    "modified_at",
    "exported_at",
    "body_text",
    "body_html",
    "body_markdown",
    "content_sha256",
    "attachments_json",
    "storage_backend",
    "metadata_storage_key",
    "metadata_storage_file_id",
    "metadata_storage_url",
    "metadata_content_sha256",
    "html_storage_key",
    "html_storage_file_id",
    "html_storage_url",
    "html_content_sha256",
    "is_deleted",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_NOTE_ATTACHMENT_COLUMNS = (
    "account",
    "note_id",
    "revision_id",
    "attachment_id",
    "filename",
    "content_type",
    "size_bytes",
    "content_sha256",
    "is_missing",
    "error",
    "storage_backend",
    "storage_key",
    "storage_file_id",
    "storage_url",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_MESSAGE_HANDLE_COLUMNS = (
    "account",
    "handle_id",
    "handle_rowid",
    "address",
    "country",
    "service",
    "uncanonicalized_id",
    "person_centric_id",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_MESSAGE_CHAT_COLUMNS = (
    "account",
    "chat_id",
    "chat_rowid",
    "guid",
    "chat_identifier",
    "service_name",
    "display_name",
    "room_name",
    "account_login",
    "style",
    "state",
    "is_archived",
    "is_filtered",
    "is_recovered",
    "is_pending_review",
    "last_read_message_at",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_MESSAGE_CHAT_HANDLE_COLUMNS = (
    "account",
    "chat_id",
    "handle_id",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_MESSAGE_COLUMNS = (
    "account",
    "message_id",
    "message_rowid",
    "handle_id",
    "service",
    "message_account",
    "body_text",
    "body_source",
    "body_decode_status",
    "body_decode_error",
    "attributed_body_sha256",
    "subject",
    "country",
    "message_type",
    "message_item_type",
    "is_from_me",
    "is_read",
    "is_sent",
    "is_delivered",
    "is_finished",
    "is_system_message",
    "is_service_message",
    "is_forward",
    "is_empty",
    "is_audio_message",
    "is_played",
    "cache_has_attachments",
    "has_unseen_mention",
    "is_spam",
    "reply_to_guid",
    "associated_message_guid",
    "associated_message_type",
    "associated_message_emoji",
    "balloon_bundle_id",
    "group_title",
    "group_action_type",
    "message_action_type",
    "message_source",
    "expressive_send_style_id",
    "message_at",
    "date_ns",
    "date_read",
    "date_delivered",
    "date_played",
    "date_edited",
    "date_retracted",
    "date_recovered",
    "is_deleted",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_MESSAGE_CHAT_MESSAGE_COLUMNS = (
    "account",
    "chat_id",
    "message_id",
    "message_date",
    "message_date_ns",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

APPLE_MESSAGE_ATTACHMENT_COLUMNS = (
    "account",
    "attachment_id",
    "attachment_rowid",
    "message_id",
    "guid",
    "original_guid",
    "filename",
    "transfer_name",
    "content_type",
    "uti",
    "mime_type",
    "total_bytes",
    "size_bytes",
    "content_sha256",
    "is_missing",
    "error",
    "is_outgoing",
    "is_sticker",
    "hide_attachment",
    "transfer_state",
    "created_at",
    "start_at",
    "storage_backend",
    "storage_key",
    "storage_file_id",
    "storage_url",
    "raw_metadata_json",
    "ingested_at",
    "sync_version",
)

AGENT_RUN_COLUMNS = (
    "run_id",
    "provider",
    "model",
    "task_type",
    "subject_id",
    "prompt_version",
    "status",
    "input_sha256",
    "final_output_json",
    "error",
    "exit_code",
    "started_at",
    "completed_at",
    "sync_version",
)

AGENT_RUN_EVENT_COLUMNS = (
    "run_id",
    "event_index",
    "stream",
    "event_type",
    "event_json",
    "text",
    "created_at",
    "sync_version",
)

AGENT_RUN_TOOL_CALL_COLUMNS = (
    "run_id",
    "event_index",
    "tool_name",
    "arguments_json",
    "result_json",
    "error",
    "started_at",
    "completed_at",
    "sync_version",
)

SLACK_TEAM_COLUMNS = (
    "account",
    "team_id",
    "team_name",
    "domain",
    "enterprise_id",
    "raw_json",
    "synced_at",
    "sync_version",
)

SLACK_ACCOUNT_IDENTITY_COLUMNS = (
    "account",
    "team_id",
    "user_id",
    "team_name",
    "url",
    "raw_json",
    "synced_at",
    "sync_version",
)

SLACK_USER_COLUMNS = (
    "account",
    "team_id",
    "user_id",
    "team_user_id",
    "name",
    "real_name",
    "display_name",
    "email",
    "is_bot",
    "is_app_user",
    "is_deleted",
    "tz",
    "raw_json",
    "synced_at",
    "sync_version",
)

SLACK_CONVERSATION_COLUMNS = (
    "account",
    "team_id",
    "conversation_id",
    "conversation_type",
    "name",
    "is_channel",
    "is_group",
    "is_im",
    "is_mpim",
    "is_private",
    "is_archived",
    "is_member",
    "creator",
    "created_at",
    "topic",
    "purpose",
    "num_members",
    "raw_json",
    "synced_at",
    "sync_version",
)
SLACK_CONVERSATION_READ_STATE_FIELDS = (
    "last_read",
    "unread_count",
    "unread_count_display",
    "is_open",
)

SLACK_CONVERSATION_MEMBER_COLUMNS = (
    "account",
    "team_id",
    "conversation_id",
    "user_id",
    "is_deleted",
    "synced_at",
    "sync_version",
)

SLACK_MESSAGE_COLUMNS = (
    "account",
    "team_id",
    "conversation_id",
    "message_ts",
    "message_datetime",
    "thread_ts",
    "parent_message_ts",
    "user_id",
    "bot_id",
    "username",
    "type",
    "subtype",
    "text",
    "blocks_json",
    "attachments_json",
    "is_thread_parent",
    "is_thread_reply",
    "reply_count",
    "reply_users_count",
    "latest_reply_ts",
    "edited_ts",
    "client_msg_id",
    "is_deleted",
    "raw_json",
    "synced_at",
    "sync_version",
)

SLACK_REACTION_COLUMNS = (
    "account",
    "team_id",
    "conversation_id",
    "message_ts",
    "reaction_name",
    "user_id",
    "reaction_count",
    "is_deleted",
    "raw_json",
    "synced_at",
    "sync_version",
)

SLACK_FILE_COLUMNS = (
    "account",
    "team_id",
    "file_id",
    "conversation_id",
    "message_ts",
    "user_id",
    "created_at",
    "name",
    "title",
    "mimetype",
    "filetype",
    "url_private",
    "size",
    "is_deleted",
    "raw_json",
    "synced_at",
    "sync_version",
)

SLACK_SYNC_STATE_COLUMNS = (
    "account",
    "team_id",
    "object_type",
    "object_id",
    "cursor_ts",
    "last_sync_type",
    "status",
    "error",
    "updated_at",
    "sync_version",
)

SLACK_ACCOUNT_STATE_ITEM_ROW_COLUMNS = (
    "source",
    "account",
    "scope_id",
    "item_id",
    "item_type",
    "item_state",
    "priority_rank",
    "latest_activity_at",
    "container_id",
    "container_name",
    "thread_id",
    "message_id",
    "actor_id",
    "actor_name",
    "title",
    "preview",
    "unread_count",
    "reason",
    "source_table",
    "drilldown_hint",
    "is_deleted",
    "synced_at",
    "sync_version",
)

@dataclass(frozen=True)
class SyncState:
    account: str
    last_history_id: int
    last_sync_type: str
    status: str
    error: str
    updated_at: datetime
