storage:
  postgres:
    postgres_url:
      env: DAGSTER_POSTGRES_URL

run_coordinator:
  module: dagster._core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 8
    dequeue_interval_seconds: 5
    dequeue_use_threads: true
    dequeue_num_workers: 4

run_monitoring:
  enabled: true
  poll_interval_seconds: 60
  start_timeout_seconds: 300
  cancel_timeout_seconds: 300
  max_runtime_seconds: 14400
