#!/usr/bin/env python3
"""Generate the Go view and documentation from the warehouse catalog.

``src/personal_data_warehouse/warehouse_catalog.json`` is the single editable
authority. The app is built from an ``app/``-only Docker context and cannot read
that file, so its Go representation is generated here and checked in.

    uv run python scripts/generate_go_warehouse_catalog.py            # write
    uv run python scripts/generate_go_warehouse_catalog.py --check    # verify

``--check`` is what the test suite runs: it fails if the checked-in Go file or
generated documentation has drifted from the catalog, so the surfaces cannot
disagree.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from personal_data_warehouse.warehouse_catalog import CATALOG  # noqa: E402

TARGET = REPO_ROOT / "app" / "internal" / "warehouse" / "catalog_gen.go"
DOC_TARGETS = (
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / "README.md",
    REPO_ROOT / "app" / "README.md",
)
PRIORITY_DOC_START = "<!-- BEGIN GENERATED TIMELINE PRIORITY CONTRACT -->"
PRIORITY_DOC_END = "<!-- END GENERATED TIMELINE PRIORITY CONTRACT -->"

HEADER = """// Code generated by scripts/generate_go_warehouse_catalog.py. DO NOT EDIT.
//
// Source of truth: src/personal_data_warehouse/warehouse_catalog.json.
// Regenerate with `uv run python scripts/generate_go_warehouse_catalog.py`;
// TestGeneratedCatalogMatchesJSON fails when this file drifts from it.

package warehouse
"""


def go_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def render() -> str:
    lines: list[str] = [HEADER]

    lines.append("// CatalogVersion is the catalog schema version this file was generated from.")
    lines.append(f"const CatalogVersion = {CATALOG.version}")
    lines.append("")

    lines.append("// StartHere is the discovery guidance the catalog carries, so the UI and")
    lines.append("// the schema overview never restate it independently.")
    lines.append("var StartHere = StartHereGuidance{")
    lines.append(f"\tSchema:   {go_string(CATALOG.start_here.schema)},")
    lines.append(f"\tHeadline: {go_string(CATALOG.start_here.headline)},")
    lines.append("\tLines: []string{")
    for line in CATALOG.start_here.lines:
        lines.append(f"\t\t{go_string(line)},")
    lines.append("\t},")
    lines.append("}")
    lines.append("")

    priorities = CATALOG.timeline_priorities
    lines.append("// TimelinePriorities is the generated priority meaning and scope contract.")
    lines.append("// Every Go-facing description and default derives from this value.")
    lines.append("var TimelinePriorities = TimelinePriorityContract{")
    lines.append(f"\tDefaultScope: {go_string(priorities.default_scope)},")
    lines.append("\tAttentionPriorities: []string{")
    for priority in priorities.attention_priorities:
        lines.append(f"\t\t{go_string(priority)},")
    lines.append("\t},")
    lines.append("\tOptimizedBM25Priorities: []string{")
    for priority in priorities.optimized_bm25_priorities:
        lines.append(f"\t\t{go_string(priority)},")
    lines.append("\t},")
    lines.append("\tTiers: []TimelinePriorityTier{")
    for tier in priorities.tiers:
        lines.append(
            "\t\t{Name: %s, Meaning: %s, TypicalRows: %s},"
            % (go_string(tier.name), go_string(tier.meaning), go_string(tier.typical_rows))
        )
    lines.append("\t},")
    lines.append(
        "\tSentinel: TimelinePriorityTier{Name: %s, Meaning: %s, TypicalRows: %s},"
        % (
            go_string(priorities.sentinel.name),
            go_string(priorities.sentinel.meaning),
            go_string(priorities.sentinel.typical_rows),
        )
    )
    lines.append("\tSelectionGuide: []TimelinePrioritySelection{")
    for entry in priorities.selection_guide:
        selected = ", ".join(go_string(priority) for priority in entry.priorities)
        lines.append(
            "\t\t{Intent: %s, Priorities: []string{%s}, Guidance: %s},"
            % (go_string(entry.intent), selected, go_string(entry.guidance))
        )
    lines.append("\t},")
    lines.append("}")
    lines.append("")

    lines.append("// Schemas is every managed schema, in presentation order:")
    lines.append("// base_* then derived_* then marts_* then timeline, then the hidden ones.")
    lines.append("var Schemas = []CatalogSchema{")
    for schema in CATALOG.schemas:
        lines.append(
            "\t{Name: %s, Layer: %s, Domain: %s, Discoverable: %s, Comment: %s},"
            % (
                go_string(schema.name),
                go_string(schema.layer),
                go_string(schema.domain),
                "true" if schema.discoverable else "false",
                go_string(schema.comment),
            )
        )
    lines.append("}")
    lines.append("")

    lines.append("// Objects is every managed warehouse object keyed by its stable logical id.")
    lines.append("// Those ids are catalog identifiers — timeline source_table values and")
    lines.append("// routing keys — never SQL tokens.")
    lines.append("var Objects = []CatalogObject{")
    for obj in CATALOG.objects:
        lines.append(
            "\t{ID: %s, Kind: %s, Layer: %s, Domain: %s, Schema: %s, Name: %s, Discoverable: %s, QueryAccess: %s, Secret: %s, Comment: %s},"
            % (
                go_string(obj.id),
                go_string(obj.kind),
                go_string(obj.layer),
                go_string(obj.domain),
                go_string(obj.schema),
                go_string(obj.name),
                "true" if obj.discoverable else "false",
                go_string(obj.query_access),
                "true" if obj.secret else "false",
                go_string(obj.comment),
            )
        )
    lines.append("}")
    lines.append("")

    lines.append("// PreviousLocations maps each object's pre-reorganization physical")
    lines.append("// `schema.name` onto its current one. It exists ONLY so an undefined-relation")
    lines.append("// error can name the new location; nothing resolves SQL through it. Delete it")
    lines.append("// (and the catalog's `previous` blocks) once the old names have faded.")
    lines.append("var PreviousLocations = map[string]string{")
    for obj in sorted(CATALOG.objects, key=lambda o: (o.previous_schema, o.previous_name)):
        if not obj.previous_schema:
            continue
        old = f"{obj.previous_schema}.{obj.previous_name}"
        new = f"{obj.schema}.{obj.name}"
        if old == new:
            continue
        lines.append(f"\t{go_string(old)}: {go_string(new)},")
    lines.append("}")
    lines.append("")

    lines.append("// RenamedTimelineSourceTables maps historical timeline.events source_table")
    lines.append("// tokens onto their current catalog id. Rows written before a rename keep")
    lines.append("// the old token until the one-shot upgrade rewrites them.")
    lines.append("var RenamedTimelineSourceTables = map[string]string{")
    for legacy, current in sorted(CATALOG.renamed_timeline_source_tables.items()):
        lines.append(f"\t{go_string(legacy)}: {go_string(current)},")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def _markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render_priority_markdown() -> str:
    """Render the human-facing mirror from the same machine contract."""
    contract = CATALOG.timeline_priorities
    lines = [
        PRIORITY_DOC_START,
        "<!-- Generated by scripts/generate_go_warehouse_catalog.py; do not edit by hand. -->",
        "",
        "| tier | what it means | typical rows |",
        "| --- | --- | --- |",
    ]
    for tier in contract.tiers:
        lines.append(
            f"| `{tier.name}` | {_markdown_cell(tier.meaning)} | "
            f"{_markdown_cell(tier.typical_rows)} |"
        )
    lines.extend(
        [
            "",
            "**Scope selection guide** — use the single `priorities` mechanism; do not add a competing scope flag:",
            "",
            "| intent | priorities | why |",
            "| --- | --- | --- |",
        ]
    )
    for entry in contract.selection_guide:
        selected = ",".join(entry.priorities) if entry.priorities else "all tiers (omit the filter)"
        lines.append(
            f"| {_markdown_cell(entry.intent)} | `{selected}` | {_markdown_cell(entry.guidance)} |"
        )
    lines.extend(
        [
            "",
            f"The default scope is **{contract.default_scope} tiers**; no priorities filter is applied. "
            f"`{contract.sentinel.name}` is not a sixth tier: {contract.sentinel.meaning}. "
            f"It describes {contract.sentinel.typical_rows} and is accepted only so an outage can be found.",
            PRIORITY_DOC_END,
        ]
    )
    return "\n".join(lines)


def replace_priority_doc(text: str, *, path: Path) -> str:
    if text.count(PRIORITY_DOC_START) != 1 or text.count(PRIORITY_DOC_END) != 1:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)} must contain exactly one generated priority marker pair"
        )
    before, tail = text.split(PRIORITY_DOC_START, 1)
    _, after = tail.split(PRIORITY_DOC_END, 1)
    return before + render_priority_markdown() + after


def _gofmt(path: Path) -> None:
    """Run gofmt so the checked-in file matches what `gofmt -l` expects.

    Map literals are aligned by gofmt, and this file is generated, so let the
    formatter own that instead of reproducing its alignment rules here.
    """
    import shutil
    import subprocess

    gofmt = shutil.which("gofmt")
    if gofmt:
        subprocess.run([gofmt, "-w", str(path)], check=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in file is stale")
    args = parser.parse_args()

    generated = render()
    if args.check:
        formatted = TARGET.parent / (TARGET.name + ".check")
        formatted.write_text(generated)
        try:
            _gofmt(formatted)
            expected = formatted.read_text()
        finally:
            formatted.unlink(missing_ok=True)
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != expected:
            print(
                f"{TARGET.relative_to(REPO_ROOT)} is out of date; run "
                "`uv run python scripts/generate_go_warehouse_catalog.py`",
                file=sys.stderr,
            )
            return 1
        stale_docs: list[Path] = []
        for path in DOC_TARGETS:
            current_doc = path.read_text()
            if replace_priority_doc(current_doc, path=path) != current_doc:
                stale_docs.append(path)
        if stale_docs:
            joined = ", ".join(str(path.relative_to(REPO_ROOT)) for path in stale_docs)
            print(
                f"generated priority documentation is out of date in {joined}; run "
                "`uv run python scripts/generate_go_warehouse_catalog.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(REPO_ROOT)} is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated)
    _gofmt(TARGET)
    for path in DOC_TARGETS:
        path.write_text(replace_priority_doc(path.read_text(), path=path))
    print(f"wrote {TARGET.relative_to(REPO_ROOT)} ({len(CATALOG.objects)} objects)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
